import math

number1=input('enter number1')
number2=input('enter number2')
number3=input('enter number3')
sum=int(number1)+int(number2)+int(number3)
print(sum)
difference=int(number1)-int(number2)-int(number3)
multiplication=int(number1)*int(number2)*int(number3)
division=int(number1)/int(number2)/int(number3)
print(difference,multiplication,division)
print(math.pow(9,3))
print(math.atan(0.39))
print(math.radians(-20))
print(math.sqrt(16))
print(math.acos(0))
print(math.degrees(90))
print(math.trunc(2.77))
print(math.floor(0.6))
print(math.tan(-90))
print(math.factorial(12))
print(math.cosh(1))
